version: '3'
services:
  app:
    build: .
    tty: true
    container_name: app
    expose:
      - "5001"
    command: gunicorn mysite.wsgi -b 0.0.0.0:5001
    volumes:
      - './:/usr/src/app'
    working_dir: '/usr/src/app'

  nginx:
    build: ./nginx
    tty: true
    container_name: nginx
    ports:
      - "80:8000"
    volumes:
      - "./media:/usr/local/media"
      - "./blog/static:/usr/local/static"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app      